version: '2'
services:
  asean-ui:
    tty: true
    stdin_open: true
    image: ${REGISTRY_PREFIX}asean-ui:dev-20180611
    ports:
      - 3001:3001
    labels:
      io.rancher.container.pull_image: always
      
