version: '2'
.catalog:
  name: "liulian"
  version: "llxia-latest-0209"
  description: "liulian"
  questions:
    - variable: "expose_gateway_port"
      description: "expose lb port."
      label: "Expose GatewayPort"
      type: "int"
      default: 3000
      required: true
    - variable: "expose_discovery_port"
      description: "expose discovery port."
      label: "Expose Discovery Port"
      type: "int"
      default: 1111
      required: true
    - variable: "expose_db_port"
      description: "expose mysql port for dev-only!."
      label: "Expose MySQL Port"
      type: "int"
      default: 13306
      required: true 
    - variable: "local_mysql_data_dir"
      description: "Local MySQL Data Directory"
      label: "Local MySQL Data Directory"
      type: "string"
      default: /var/lib/mysql
      required: true 
services:
  discovery:
    scale: 1
    start_on_create: true
  config:
    scale: 1
    start_on_create: true
  account:
    scale: 1
    start_on_create: true
  opuser:
    scale: 1
    start_on_create: true
  common:
    scale: 1
    start_on_create: true
  product:
    scale: 1
    start_on_create: true
  icrm:
    scale: 1
    start_on_create: true
  gateway:
    scale: 1
    start_on_create: true
  gateway-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: gateway
        source_port: 3000
        target_port: 5555
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  order:
    scale: 1
    start_on_create: true
  payment:
    scale: 1
    start_on_create: true
  esimbusic:
    scale: 1
    start_on_create: true
  db:
    scale: 1
    start_on_create: true
  db-init:
    scale: 1
    start_on_create: true